export { Octivas } from "./client";
export type { OctivasConfig } from "./client";
export type {
  ContentFormat,
  Location,
  PageMetadata,
  PageContent,
  SearchResultItem,
  ScrapeParams,
  ScrapeResponse,
  BatchScrapeParams,
  CrawlParams,
  MapParams,
  MapLink,
  MapResponse,
  SearchParams,
  SearchResponse,
  ErrorResponse,
  JobProgress,
  JobError,
  JobSubmitResponse,
  JobStatusResponse,
  JobListItem,
  JobListResponse,
  ListJobsOptions,
} from "./types";
export {
  OctivasError,
  AuthenticationError,
  BadRequestError,
  ForbiddenError,
  NotFoundError,
  RateLimitError,
  ServerError,
} from "./errors";
